# Generated by Django 3.1.4 on 2021-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210217_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='image',
            field=models.ImageField(blank=True, upload_to='usertype_img'),
        ),
    ]
