# Generated by Django 3.1.4 on 2021-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210222_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
