# Generated by Django 3.1.7 on 2021-04-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
