# Generated by Django 3.1.7 on 2021-04-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userprofile_passward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
