# Generated by Django 3.2.2 on 2021-07-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210707_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='online_status',
            field=models.BooleanField(default=True),
        ),
    ]
