# Generated by Django 3.1.7 on 2021-05-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_mutechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutechat',
            name='mute_status',
        ),
    ]
