# Generated by Django 3.1.4 on 2021-02-17 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailor_speci', models.CharField(blank=True, max_length=50, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailor_speci_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targeted_customer', models.CharField(blank=True, max_length=10, null=True)),
                ('tailor_staff_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ship_outside_country', models.BooleanField(default=False)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_services_country', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_created_by', to=settings.AUTH_USER_MODEL)),
                ('tailor_speci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_tailor_speci', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
