# Generated by Django 3.1.4 on 2021-02-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierservices',
            name='tailor_speci_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_tailor_speci', to='services.tailorspecification'),
        ),
    ]
