# Generated by Django 3.1.4 on 2021-02-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210217_1844'),
        ('services', '0002_auto_20210217_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierservices',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_services_country', to='account.countries'),
        ),
    ]
