# Generated by Django 3.1.4 on 2021-02-20 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_auto_20210217_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierservices',
            name='tailor_experience',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='supplierservices',
            name='tailor_staff_gender',
        ),
        migrations.RemoveField(
            model_name='supplierservices',
            name='targeted_customer',
        ),
        migrations.CreateModel(
            name='TargetedCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetedcustomer_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='supplierservices',
            name='tailor_staff_gender',
            field=models.ManyToManyField(related_name='tailor_staff_gender', to='services.TargetedCustomer'),
        ),
        migrations.AddField(
            model_name='supplierservices',
            name='targeted_customer',
            field=models.ManyToManyField(related_name='targeted_customer', to='services.TargetedCustomer'),
        ),
    ]
