# Generated by Django 3.1.7 on 2021-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210224_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorspecification',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='services_images'),
        ),
    ]
