# Generated by Django 3.1.7 on 2021-03-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_tailorspecification_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierservices',
            name='tailor_speci_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_tailor_speci', to='services.tailorspecification'),
        ),
    ]
