# Generated by Django 3.1.7 on 2021-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_tailorspecification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailorspecification',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
