# Generated by Django 3.1.7 on 2021-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210309_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorspecification',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
