# Generated by Django 3.1.7 on 2021-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
