# Generated by Django 3.1.7 on 2021-02-26 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo_images')),
                ('header_bg_img', models.ImageField(blank=True, upload_to='header_bg_img_images')),
                ('service_counter', models.IntegerField(blank=True, null=True)),
                ('product_counter', models.IntegerField(blank=True, null=True)),
                ('supplier_counter', models.IntegerField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, upload_to='about_images')),
                ('about_title', models.CharField(blank=True, max_length=20, null=True)),
                ('about_description', models.CharField(blank=True, max_length=300, null=True)),
                ('fb', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='How_it_works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='how_it_work_images')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_work_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
