# Generated by Django 3.1.7 on 2021-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='how_it_works',
            name='line_image',
            field=models.ImageField(blank=True, null=True, upload_to='how_it_work_images'),
        ),
    ]
