# Generated by Django 3.1.7 on 2021-02-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0002_how_it_works_line_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_settings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='header_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg_img_images'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
