# Generated by Django 3.1.7 on 2021-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0003_auto_20210226_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images'),
        ),
    ]
