# Generated by Django 3.1.7 on 2021-02-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0004_auto_20210226_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='product_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_images'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='service_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_images'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='supplier_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_images'),
        ),
    ]
