# Generated by Django 3.1.7 on 2021-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0005_auto_20210227_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='header_service_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_images'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='header_supplier_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_images'),
        ),
    ]
