# Generated by Django 3.1.7 on 2021-04-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0006_auto_20210227_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='customer_dashbaord_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg_img_images'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='find_products_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg_img_images'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='find_services_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg_img_images'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='find_supplier_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg_img_images'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='supplier_dashboard_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg_img_images'),
        ),
    ]
