# Generated by Django 3.1.7 on 2021-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0007_auto_20210414_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='about_us_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg_img_images'),
        ),
    ]
