# Generated by Django 3.1.7 on 2021-03-31 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='', max_length=150)),
                ('smtp_username', models.CharField(default='', max_length=150)),
                ('smtp_port', models.CharField(default='', max_length=150)),
                ('smtp_password', models.CharField(default='', max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Email Setting',
            },
        ),
    ]
