# Generated by Django 3.1.7 on 2021-02-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_auto_20210223_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
                ('option_a', models.CharField(max_length=100, null=True)),
                ('option_b', models.CharField(max_length=100, null=True)),
                ('option_c', models.CharField(max_length=100, null=True)),
                ('option_d', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
                ('priority_type', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_created_by', to=settings.AUTH_USER_MODEL)),
                ('question_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_for', to='account.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.questionstable')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
