# Generated by Django 3.1.7 on 2021-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstable',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
