# Generated by Django 3.1.7 on 2021-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findsupplier', '0002_auto_20210322_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistraionFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
