# Generated by Django 3.1.7 on 2021-05-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findsupplier', '0003_registraionfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahespayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registraionfees',
            name='currency_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
