# Generated by Django 3.1.7 on 2021-02-27 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_auto_20210223_1837'),
        ('products', '0003_fabric_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('width_size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('other_description', models.TextField(blank=True, max_length=150, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('Product_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='products.product_subcategory')),
                ('country_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.countries')),
                ('fabrictype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_type', to='products.fabric_type')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_category')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.season')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('washing_method', models.ManyToManyField(blank=True, null=True, to='products.Washing_method')),
            ],
        ),
    ]
