# Generated by Django 3.1.7 on 2021-03-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210303_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='color',
            field=models.TextField(null=True),
        ),
    ]
