# Generated by Django 3.1.7 on 2021-03-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_supplierproduct_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='width_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
