# Generated by Django 3.1.7 on 2021-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210312_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_text', models.CharField(blank=True, max_length=30, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
