# Generated by Django 3.1.7 on 2021-04-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_countrycurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycurrency',
            name='unit_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
