# Generated by Django 3.1.7 on 2021-04-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_supplierproduct_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='other_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
