# Generated by Django 3.1.7 on 2021-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210405_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='brand_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
